### ISSUE TITLE
Example project not starting

### ISSUE THREAD

**Issue by Amantel** [forrestjs/forrestjs#22]
Got error `UNHANDLED REJECTION Error: error Command failed with exit code 1` after trying the example.

Setup: 
yarn version 1.22.4
node version 14.4.0

Log: 
```
npx forrest run my-new-ssr-app
npx: installed 162 in 13.033s
yarn run v1.22.4
$ npm run clean && npm run build && cross-env NODE_ENV=production node index
> forrest-starter-universal@0.1.0 clean /home/tel/Desktop/gigs_general/ssr_test/my-new-ssr-app
> rm -rf node_build && rm -rf build
> forrest-starter-universal@0.1.0 build /home/tel/Desktop/gigs_general/ssr_test/my-new-ssr-app
> npm run build:app && npm run build:node
> forrest-starter-universal@0.1.0 build:app /home/tel/Desktop/gigs_general/ssr_test/my-new-ssr-app
> react-scripts build && mkdir -p node_build && rm -rf ./node_build/app && mv build node_build/app
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
UNHANDLED REJECTION Error: error Command failed with exit code 1.
    at ChildProcess.<anonymous> (/home/tel/.npm/_npx/6824/lib/node_modules/forrest/lib/utils.js:35:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  spawnCode: 1
}
```

**Comment by marcopeg** [comment]
We are not maintaining the ssr anymore.
NextJS covers that succesfully.
